---
- name: Generate a new token
  command: kubeadm token generate
  delegate_to: "{{ hostvars[groups['bamdad'][0]]['ansible_host'] }}"
  register: token_output


- name: Get the join command for worker nodes
  command:
    cmd: kubeadm token create {{ token_output.stdout }} --print-join-command
  delegate_to: "{{ hostvars[groups['bamdad'][0]]['ansible_host'] }}"
  register: worker_join_command_output



- name: Save the worker join command to a variable
  ansible.builtin.set_fact:
    worker_join_command: "{{ worker_join_command_output.stdout }}"


- name: Join the worker nodes to the Kubernetes cluster
  shell: "{{ worker_join_command }}"
  when: ("'worker' in mode")


- name: craete adirectory in $HOME/.kube/
  file:
    path: $HOME/.kube
    state: directory
    owner: root
    group: root
    mode: 0644


- name: copy kubernetes config to home
  copy:
    src: /etc/kubernetes/kubelet.conf
    dest: $HOME/.kube/config
    owner: root
    group: root
    mode: 0644
    remote_src: yes



